# Site settings
title: Chengqi Liu
email: 1@wejex.me
description: >
  Freedom is not free
baseurl: "/material-jekyll-theme"
url: "http://wejex.me"
fixedNav: 'true' # true or false
theme: blue # green, blue, orange, purple, grey
twitterUsername: hybrid_alex
githubUsername: alexcarpenter
dribbbleUsername:
codepenUsername:

# Build settings
permalink: /:year/:month/:title
markdown: kramdown
include: [_pages]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed
